name: Read new files on commit

on:
  push:
    branches: master

jobs:
  read-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get list of new files
      id: files
      run: 
          curl --location --request GET 'https://968c-49-204-19-20.ngrok-free.app/api/create-action?>
--data-raw ''


