name: Get Modified Files in Latest Commit
on: push

jobs:
  get-modified-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Latest Commit SHA
        id: latest_commit_sha
        run: |
          echo "::set-output name=sha::$(curl -s -H \"Accept: application/vnd.github.v3+json\" https://api.github.com/repos/umranBatuwah/Demo_Repository/commits/main | jq -r '.sha')"

      - name: Get Modified Files
        id: modified_files
        run: |
          curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/umranBatuwah/Demo_Repository/commits/${{ steps.latest_commit_sha.outputs.sha }}/files | jq -r '.[] | select(.status == "modified") | .filename'
          curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/umranBatuwah/Demo_Repository/${{ steps.latest_commit_sha.outputs.sha }}/files | jq -r '.[] | select(.status == "modified") | .filename, .patch'
