name: Send Curl Request
on:
  push:
    branches: [ main ]

jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request
        run: |
          curl http://localhost:5057/api/create-bulk-git
