name: My Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get modified files
        run: |
          for file in ${{ toJson(github.event.head_commit.modified) }}; do
            echo "Modified file path: $file"
          done

