name: Send Curl Request
on:
  push:
    branches: master

jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request
        run: |
         curl --location --request GET 'https://00f0-49-204-19-20.in.ngrok.io/api/create-bulk-git?jsonFilePath=https://github.com/AppkubeCloud/json-data.git' \--data-raw ''
