name: Get Latest Commit
on: push

jobs:
  get-latest-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Latest Commit
        run: |
          curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/umranBatuwah/Demo_Repository/commits/main | jq '.sha'
